### ISSUE TITLE
Access-Control-Allow-Origin error

### ISSUE THREAD

**Issue by mstar95** [sz-piotr/pik-projekt#10]
$.ajax({
        url: "http://localhost:9000/users"
Nie działa na Google Chrome, sypie errorem Access-Control-Allow-Origin.
Na Internet Explorer dziala

**Comment by sz-piotr** [comment]
Żeby rozwiązać ten błąd dobrze trzeba zrobić dwie rzeczy:

1. Zrobić na frontendzie proxy dla wszystkich requestów ajaxowych
2. Aby to było możliwe wszystkie requesty ajaxowe powinny mieć prefix w url np. api

Ostatecznie dobrze byłoby też skonfigurować żeby produkcyjnie to backend serwował pliki z fontendu bo wtedy proxy nie będzie potrzebne.
