### ISSUE TITLE
Autoryzacja sie nie udaje

### ISSUE THREAD

**Issue by mstar95** [sz-piotr/pik-projekt#14]
axios przy wyslaniu posta z poprawnymi credentialsami zwraca 401 - do zbadania

**Comment by sz-piotr** [comment]
Trzeba spojrzeć co się wysyła w devtoolsach. Może spróbować: https://github.com/mzabriskie/axios/blob/master/README.md#browser

**Comment by mstar95** [comment]
http://stackoverflow.com/questions/41555690/axios-basic-authorization-not-going-through-in-reactjs 
:(

**Comment by sz-piotr** [comment]
Zobaczę to jutro jeszcze. Najwyżej zmienimy bibliotekę ale aż mi się nie chce wierzyć że pierwszy request nie działa

**Comment by sz-piotr** [comment]
Źle wysyłałeś requesta
