### ISSUE TITLE
Lista materiałów szkoleniowych

### ISSUE THREAD

**Issue by jaklan** [sz-piotr/pik-projekt#17]
tutoriale, manuale, książki, blogi na podstawie których zespół będzie uczył się wymienionych
technologii

**Comment by robcioo** [comment]
https://spring.io/
http://stackoverflow.com/
https://kotlinlang.org/docs/reference/classes.html
https://help.ubuntu.com/community/PostgreSQL

**Comment by mstar95** [comment]
^
